// frontend/src/app/components/fact/fact.component.ts
import { Component, Input } from '@angular/core'

@Component({
    selector: 'app-fact',
    templateUrl: './fact.component.html',
    styleUrls: ['./fact.component.scss']
})
export class FactComponent {
    @Input() id: string = ''
    @Input() text: string = ''
    @Input() category: string = ''
    @Input() source: string = ''
}

<p class="text">{{ text }}</p>
<a class="source" href="{{ source }}">(source)</a>

// frontend/src/components/Fact.tsx
import React from 'react'

export interface IFact {
    Id: string
    Text: string
    Category: string
    Source: string
    Image: string
}

export const Fact = (fact: IFact) => {
    console.log('Fact', fact)
    return (
        <div className="fact">
            <p>{fact.Text}</p>
            <a href={fact.Source}>Source</a>
        </div>
    )
}
